version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: captiveportal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web-network

  webapp:
    build:
      context: ./webapp
    container_name: webapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/captiveportal
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  postgres_data:

