version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: captiveportal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"

  webapp:
    build:
      context: ./webapp
    container_name: webapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/captiveportal
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - db
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
